<?php $helper = Mage::helper('Cadena_Product'); ?>
<div id="slider">
	<div class="slidercontrolwr">
		<div class="slidercontrol"><a title="Slide 1" href="#section1">1</a> <a title="Slide 2" href="#section2">2</a> <a title="Slide 3" href="#section3">3</a> <a title="Slide 4" href="#section4">4</a> <a title="Slide 5" href="#section5">5</a></div>
	</div>
	<div class="scroller">
		<div class="content">
			<div id="section1" class="sectionslide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" 
			value="<?php
                        $currentUrl = Mage::helper('core/url')->getCurrentUrl();
                        if($currentUrl===$helper->getOnSaleUrl('Samsung')):
                            echo $helper->getNotOnSaleUrl();
                        echo "\"checked=\"checked";
                        else:
                            echo $helper->getOnSaleUrl('Samsung');
                        endif;
                    ?>" onclick="setLocation(this.value)">
            </div>
			<div id="section2" class="sectionslide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" /></div>
			<div id="section3" class="sectionslide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" /></div>
			<div id="section4" class="sectionslide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" /></div>
			<div id="section5" class="sectionslide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" /></div>
		</div>
	</div>
</div>
<script charset="utf-8" type="text/javascript">// <![CDATA[
    var my_glider = new Glider('slider', {duration:0.5, autoGlide: true, frequency: 4, initialSection: 'section1'});   
// ]]></script>

<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();

 $_productCollection->addAttributeToSelect('name')
                      ->addAttributeToSelect('price')
                      ->addAttributeToSelect('special_price')
                      ->addAttributeToSelect('brand_name')
                      ->addAttributeToFilter(array(
                            array('attribute'=>'brand_name', 'eq'=>$_GET['brand_name'])
                      )); 
Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
        <?php // List mode ?>
            <?php $_iterator = 0; ?>
            <ol class="products-list" id="products-list">
                <?php foreach ($_productCollection as $_product): ?>
                    <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
                        <?php // Product Image ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $_product->getImageUrl(); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                        <?php // Product description ?>
                        <div class="product-shop">
                            <div class="f-fix">
                                <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                                <?php if($_product->getRatingSummary()): ?>
                                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                                <?php endif; ?>
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if($_product->isSaleable()): ?>
                                    <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                                <?php else: ?>
                                    <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                                <?php endif; ?>
                                <div class="desc std">
                                    <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                                </div>
                                <ul class="add-to-links" style="margin:0; padding-left:0; list-style: none;">
                                    <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                        <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                                    <?php endif; ?>
                                    <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                        <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                                    <?php endif; ?>
                                </ul>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>