<?php $helper = Mage::helper('Bekommerce_Product'); ?>
<div class="swiper-container">
	<div class="swiper-wrapper">
       <!-- <div id="section1" class="swiper-slide"><input type="image" src="http://127.0.0.1/magento2/skin/frontend/default/f001_red/images/slider/slider1.jpg" 
                 value="<?php
                 $currentUrl = Mage::helper('core/url')->getCurrentUrl();
                 if($currentUrl===$helper->getOnSaleUrl('Samsung')):
                    echo $helper->getNotOnSaleUrl();
                echo "\"checked=\"checked";
                else:
                    echo $helper->getOnSaleUrl('Samsung');
                endif;
                ?>" onclick="setLocation(this.value)">
        </div>-->
        <div id="section2" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/be1.jpg') ?>" /></div>
        <div id="section3" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/be2.jpg') ?>" /></div>
        <div id="section4" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/mali1.jpg') ?>" /></div>
        <div id="section5" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/mali2.jpg') ?>" /></div>
         <div id="section6" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/haby1.jpg') ?>" /></div>
        <div id="section7" class="swiper-slide"><input type="image" class="slider-image" src="<?php echo $this->getSkinUrl('images/haby2.jpg') ?>" /></div>
	</div>
</div>
<script charset="utf-8" type="text/javascript">// <![CDATA[
    var swiper = new Swiper('.swiper-container', {
        autoplay: 5000,
        loop: true,
        speed: 1000,
        height: 380
    });   
// ]]></script>

<section class="ico-brands">
    <section class="image-ico-bra" id="bra1">
        <img src="<?php echo $this->getSkinUrl('images/mali.png') ?>" style="margin-bottom: 15%;">
    </section>
    <section class="image-ico-bra" id="bra2">
        <img src="<?php echo $this->getSkinUrl('images/haby.png') ?>" style="margin-bottom: 15%;">
    </section>
    <section class="image-ico-bra" id="bra3">
        <img src="<?php echo $this->getSkinUrl('images/bormioli.png') ?>">
    </section>
    <section class="image-ico-bra" id="bra4">
        <img src="<?php echo $this->getSkinUrl('images/kibys.png') ?>">
    </section>
</section>
<!--
<?php
$_productCollection = Mage::getModel('catalog/product')->getCollection();

 $_productCollection->addAttributeToSelect('name')
                      ->addAttributeToSelect('price')
                      ->addAttributeToSelect('special_price')
                      ->addAttributeToSelect('brand_name')
                      ->addAttributeToFilter(array(
                            array('attribute'=>'brand_name', 'eq'=>$_GET['brand_name'])
                      )); 
Mage::getModel('review/review')->appendSummary($_productCollection);

$_helper = $this->helper('catalog/output');
?>

<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
    <div class="category-products">
    <?php echo $this->getToolbarHtml() ?>
    <?php // List mode ?>
    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <p class="product-image">
                <a href="<?php echo $this->getUrl('ajax/product/quickview/id/' . $_product->getId()) ?>" rel="nofollow" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="ajax"><?php echo $this->__('Quick view') ?></a>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>                
            </p>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <?php if($_product->getRatingSummary()): ?>
                    <?php echo $this->getReviewsSummaryHtml($_product) ?>
                    <?php endif; ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->isSaleable()): ?>
                        <p><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></p>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <div class="clear"></div>
                    <div class="desc std">
                        <?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>

    <?php else: ?>

    <?php // Grid Mode ?>

    <?php $_collectionSize = $_productCollection->count() ?>
    <?php $_columnCount = $this->getColumnCount(); ?>
    <?php $i=0; foreach ($_productCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <p class="product-image">
                    <a href="<?php echo $this->getUrl('ajax/product/quickview/id/' . $_product->getId()) ?>" rel="nofollow" title="<?php echo $this->escapeHtml($_product->getName()) ?>" class="ajax"><?php echo $this->__('Quick view') ?></a>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                            <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                    </a>
                </p>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
                <?php if($_product->getRatingSummary()): ?>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                <?php endif; ?>
                <?php echo $this->getPriceHtml($_product, true) ?>
                <div class="actions">
                    <?php if($_product->isSaleable()): ?>
                        <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                    <?php else: ?>
                        <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    <?php endif; ?>

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>
</div>
<?php endif; ?>-->